# -*- coding: utf-8 -*-
"""Reservas: onde reservar, contato, antecedência e valor (pesquisa de 29/09/2026).

Cada reserva aparece em três lugares do site:
- na página "Reservas", ordenada pelo prazo sugerido;
- numa caixinha junto do lugar (restaurante, ponto turístico, opção de travessia ou de Réveillon);
- como atalho na parada do dia em que o lugar entra no roteiro.

Campos
- uso: data em que o grupo vai ao lugar; com antecedencia_dias, o site calcula o prazo sugerido.
- em: onde a caixinha aparece. Chaves possíveis:
    "rest"      nomes exatos em dados.RESTAURANTES
    "ponto"     nomes exatos dos pontos dos blocos (dados.CIDADES)
    "extra"     nomes exatos dos extras de Buenos Aires
    "travessia" nomes exatos em dados.TRAVESSIA
    "reveillon" letras das opções em dados.REVEILLON ("A", "B", "C")
    "dia"       ids dos dias; o atalho vai na parada cujo texto cita um dos "termos"
- precisa: "obrigatória", "recomendada", "não aceita" ou "não precisa".
Qualquer texto com n/c vira o selo "não confirmado".
"""

def Rz(chave, nome, cidade, categoria, uso, quando, em, precisa, como, antecedencia, valor, obs="", link="",
       whatsapp="", telefone="", email="", instagram="", dias=None, termos=None, fontes=(), confianca=""):
    return {"chave": chave, "nome": nome, "cidade": cidade, "categoria": categoria, "uso": uso, "quando": quando,
            "em": em, "termos": termos or [nome], "precisa": precisa, "como": como, "link": link,
            "whatsapp": whatsapp, "telefone": telefone, "email": email, "instagram": instagram,
            "antecedencia": antecedencia, "antecedencia_dias": dias, "valor": valor, "obs": obs,
            "fontes": list(fontes), "confianca": confianca}


RESERVAS = [
    # ------------------------------------------------------------------ Montevidéu
    Rz("la-perdiz", "La Perdiz", "mvd", "Restaurante", "2026-12-26", "Sáb 26/12 · jantar",
       {"rest": ["La Perdiz"], "dia": ["d26"]}, "recomendada",
       "Só por telefone: o site avisa que as reservas são únicamente telefónicas.",
       "O site não informa. Avaliações recomendam reservar porque guardam poucas mesas. Sugestão nossa: ligar 2 semanas antes.",
       "Cerca de US$ 20 (≈ R$ 110) por prato, com cubierto; vinho local cerca de US$ 17 a garrafa (avaliação de 2024).",
       "Fica na Guipúzcoa 350, em Punta Carretas, ao lado do García (não em Pocitos). Sábado: 19h–1h.",
       link="https://laperdizrestaurant.com/", telefone="+598 2711 8963", email="contacto@laperdizrestaurant.com",
       instagram="@laperdizrestaurant", dias=14,
       fontes=["https://laperdizrestaurant.com/", "https://www.tripadvisor.com/Restaurant_Review-g294323-d1529010-Reviews-La_Perdiz_Restaurant_Parrillada-Montevideo_Montevideo_Department.html"],
       confianca="média"),
    Rz("baar-fun-fun", "Baar Fun Fun", "mvd", "Restaurante", "2026-12-26", "Só sáb 26/12 à noite (fecha domingo e segunda)",
       {"rest": ["Baar Fun Fun"], "dia": ["d26"]}, "recomendada",
       "Formulário no site de reservas (tem versão em português); a confirmação chega por e-mail em até 24h.",
       "O site pede reserva com antecedência, sem dizer quantos dias. Sugestão nossa: 3 semanas.",
       "Ticket artístico por pessoa (era UYU 390 em 2022; valor atual n/c), mais o consumo.",
       "Abre às 18h15; o show de tango começa por volta das 21h45; a reserva fica garantida até as 21h. Fecha domingo "
       "e segunda e está bloqueado em 24, 25 e 31/12 e 01/01.",
       link="https://reservas.barfunfun.com/pt", telefone="+598 2915 8005", email="reservasfunfun@gmail.com",
       instagram="@baarfunfun", dias=21, termos=["Baar Fun Fun"],
       fontes=["https://barfunfun.com/", "https://reservas.barfunfun.com/", "https://www.melhoresdestinos.com.br/baar-fun-fun-montevideu.html"],
       confianca="alta"),
    Rz("el-palenque", "El Palenque (Mercado del Puerto)", "mvd", "Restaurante", "2026-12-27", "Dom 27/12 · almoço",
       {"rest": ["El Palenque"], "dia": ["d27"]}, "recomendada",
       "Telefone ou e-mail; o site próprio estava fora do ar em 29/09.",
       "Sem informação de antecedência. Domingo é o dia mais cheio do mercado.",
       "UYU 1.600 a 2.200 por pessoa (≈ R$ 210 a 285), mais cubierto de UYU 210.",
       "O interior do mercado funciona só no almoço, mais ou menos das 9h às 17h. Estrangeiros podem pedir devolução do IVA.",
       telefone="+598 2917 0190", email="reservas@elpalenque.com.uy", instagram="@mercadodelpuertouy",
       termos=["El Palenque"],
       fontes=["https://www.mercadodelpuerto.com.uy/", "https://saliracomer.com/index.php/s/restaurant/217"],
       confianca="baixa"),
    Rz("la-pulperia", "La Pulpería", "mvd", "Restaurante", "2026-12-27", "Almoço de dom 27/12 (jantar só de terça a sexta)",
       {"rest": ["La Pulpería"], "dia": ["d27"]}, "não aceita",
       "Não aceita reserva: as mesas são por ordem de chegada (site oficial).",
       "Não se aplica; cheguem antes de abrir.",
       "Porção UYU 810 a 900 (≈ R$ 105 a 117); meia porção UYU 590 a 665; entradas UYU 250 a 540.",
       "Jantar só de terça a sexta, 19h–0h; sábado e domingo, só almoço, 12h–16h; fecha segunda. Salão para cerca de 30 pessoas.",
       link="https://www.lapulperia.com.uy/", telefone="+598 2710 8657", instagram="@lapulperiaparrillada",
       fontes=["https://www.lapulperia.com.uy/", "https://www.instagram.com/lapulperiaparrillada/"], confianca="alta"),
    Rz("teatro-solis", "Teatro Solís (visita guiada)", "mvd", "Atração", "2026-12-27", "Dom 27/12 · visita às 16h",
       {"ponto": ["Teatro Solís"], "dia": ["d27"]}, "não precisa",
       "Ingresso só na bilheteria, no próprio dia (abre às 15h); não há venda online das visitas.",
       "Comprem no dia; cheguem antes das 15h.",
       "UYU 400 para estrangeiros (≈ R$ 52); 50% de desconto com o comprovante digital da Tasa Turística; quarta grátis.",
       "Sábado e domingo às 15h e 16h, com opção em português. Em 2022 as visitas foram suspensas de 19 a 24/12: confirmem em dezembro.",
       link="https://www.teatrosolis.org.uy/categoria/Horarios-119", whatsapp="+598 99 186 951",
       email="info@teatrosolis.org.uy", instagram="@teatrosolis", termos=["Teatro Solís"],
       fontes=["https://www.teatrosolis.org.uy/auc.aspx?1390=", "https://www.teatrosolis.org.uy/categoria/Horarios-119"],
       confianca="alta"),
    Rz("palacio-salvo", "Palacio Salvo (visita guiada)", "mvd", "Atração", "2026-12-27", "Data de dezembro definida pela RedTickets",
       {"ponto": ["Palacio Salvo"], "dia": ["d27"]}, "obrigatória",
       "Ingressos só pela RedTickets; há um evento de visitas por mês, com data, horário e idioma.",
       "Comprem assim que sair o evento de dezembro (em 29/09 só havia setembro). Sugestão nossa: acompanhar a partir de novembro.",
       "UYU 600 por pessoa, com taxa (≈ R$ 78); de 6 a 12 anos UYU 300.",
       "Cerca de 45 min; sobe ao terraço do 25º andar e termina no Museo del Tango; tem escadas; até 9 ingressos por compra.",
       link="https://redtickets.uy/productor/PalacioSalvo", telefone="+598 97 734 525",
       email="palaciosalvooficial@gmail.com", dias=30, termos=["Palacio Salvo"],
       fontes=["https://redtickets.uy/productor/PalacioSalvo", "https://www.descubrimontevideo.uy/palacio-salvo"],
       confianca="alta"),
    Rz("mirador", "Mirador Panorámico", "mvd", "Atração", None, "Livre, perto da Av. 18 de Julio",
       {"ponto": ["Mirador Panorámico"]}, "obrigatória",
       "Ingresso grátis com QR na agenda online da Intendencia; um QR vale para até 10 pessoas; pode ser no próprio dia.",
       "Pode ser no dia. Em 29/09 a agenda de dezembro ainda não estava aberta.",
       "Grátis.",
       "Todos os dias, 11h–19h; fecha com alerta meteorológico amarelo, laranja ou vermelho.",
       link="https://tramites.montevideo.gub.uy/aplicacion/mirador-panoramico", whatsapp="+598 99 019 500",
       email="panoramico@imm.gub.uy",
       fontes=["https://montevideo.gub.uy/area-tematica/turismo/mirador-panoramico"], confianca="alta"),
    Rz("garcia", "García Parrilla", "mvd", "Restaurante", "2026-12-28", "Seg 28/12 · jantar (ou dom 27/12, se trocarem)",
       {"rest": ["Garcia Parrilla"], "dia": ["d27", "d28"]}, "recomendada",
       "WhatsApp da unidade Punta Carretas (botão Reservar Mesa no site) ou telefone. Aceita grupos e tem sala privativa.",
       "O site não informa. Sugestão nossa para 6 pessoas na alta temporada: 3 semanas antes.",
       "Baby beef UYU 1.090 (≈ R$ 142); entradas UYU 850 a 1.290; sobremesas UYU 295 a 450 (cardápio de dez/2025).",
       "Aberto todos os dias, 9h–2h. Três horas grátis no estacionamento do Punta Carretas Shopping.",
       link="https://garcia.net.com.uy/punta-carretas/", whatsapp="+598 92 001 967", telefone="+598 2710 1881",
       instagram="@garciauruguay", dias=21, termos=["García Parrilla", "Garcia Parrilla"],
       fontes=["https://garcia.net.com.uy/punta-carretas/", "https://garcia.net.com.uy/menu/"], confianca="alta"),
    Rz("legislativo", "Palacio Legislativo (visita guiada)", "mvd", "Atração", "2026-12-28", "Seg 28/12 · visita às 11h",
       {"ponto": ["Palacio Legislativo"], "dia": ["d28"]}, "não precisa",
       "Turista não agenda: chega no horário e paga na hora, só em dinheiro.",
       "Sem agendamento; cheguem alguns minutos antes.",
       "US$ 3 (≈ R$ 17) ou UYU 140 por estrangeiro, só em dinheiro.",
       "Segunda a sexta às 11h e 16h (2026), em espanhol, português ou inglês. No verão passado foi 11h30 e 15h: confirmem.",
       link="https://parlamento.gub.uy/sobreelparlamento/palacio/visitas", telefone="+598 2924 1783",
       email="protocolo@parlamento.gub.uy", instagram="@parlamentouy", termos=["Legislativo"],
       fontes=["https://www.instagram.com/reel/DS2yv2DgBef/", "https://x.com/Parlamento_UY/status/2092678694888145309"],
       confianca="média"),
    Rz("museo-andes", "Museo Andes 1972", "mvd", "Atração", "2026-12-28", "Seg 28/12 · tarde",
       {"ponto": ["Museo Andes 1972"], "dia": ["d28"]}, "não precisa",
       "Ingresso sem horário marcado; dá para comprar online no site ou na RedTickets.",
       "Não precisa comprar antes.",
       "US$ 8 por adulto (≈ R$ 44); acima de 65 anos US$ 6.",
       "Fecha aos domingos; 24 e 31/12 abre só das 10h às 13h.",
       link="https://mandes.uy/tickets/", whatsapp="+598 97 271 972", telefone="+598 2916 9461",
       email="museoandes1972@gmail.com", instagram="@museoandes1972", termos=["Andes 1972"],
       fontes=["https://mandes.uy/", "https://mandes.uy/en/tickets/"], confianca="alta"),
    # ------------------------------------------------------------------ Travessia
    Rz("buquebus", "Buquebus direta (Montevidéu → Buenos Aires)", "mvd", "Transporte", "2026-12-29", "Ter 29/12 · 11h ou 20h",
       {"travessia": ["Buquebus direta"], "dia": ["d29"]}, "obrigatória",
       "Site da Buquebus, WhatsApp, telefone ou lojas (porto, Tres Cruces e Punta Carretas Shopping).",
       "As vendas para 29/12 já estão abertas e o preço é dinâmico. Sugestão nossa: comprar as 6 passagens até o fim de outubro.",
       "Por pessoa, só ida, saída às 11h: Econômica UYU 3.222 (≈ R$ 420), Turista 3.850, Business 5.023, Primeira 6.496. "
       "Saída às 20h: Econômica UYU 3.393 (consulta de 29/09/2026).",
       "A Econômica não tem reembolso e a alteração custa US$ 30; as tarifas Programada e Flexible têm regras melhores.",
       link="https://www.buquebus.com/uy?origin=MVD&destination=BUE&departureDate=29-12-2026&adults=1",
       whatsapp="+54 9 11 2493-5214", telefone="(2) 130", instagram="@buquebus", dias=60, termos=["Buquebus"],
       fontes=["https://www.buquebus.com/uy", "https://www.buquebus.com/info/puntos-de-venta-uy"], confianca="alta"),
    Rz("colonia-express", "Colonia Express (via Colônia)", "mvd", "Transporte", "2026-12-29", "Ter 29/12 · 6h ou 14h30",
       {"travessia": ["Colonia Express"]}, "obrigatória",
       "Site oficial, WhatsApp, telefone ou pontos de venda; ônibus até Colônia e depois barco.",
       "Vendas abertas; a tarifa mais barata já aparece como 'quedan pocos'. Sugestão nossa: comprar até o fim de outubro.",
       "Por pessoa, só ida: Super Económica UYU 3.676 (≈ R$ 478), Super Express 3.952, Super Flex 4.251 (29/09/2026).",
       "Saídas às 6h (chega 10h45) e 14h30 (chega 19h15). Super Económica sem reembolso depois de 24h da compra; Super Flex permite alterações.",
       link="https://www.coloniaexpress.com/es/uy/", whatsapp="+598 97 900 656", telefone="+598 2403 8050",
       email="atencionalcliente@coloniaexpress.com", instagram="@coloniaexpress", dias=60,
       fontes=["https://www.coloniaexpress.com/es/uy/"], confianca="alta"),
    # ------------------------------------------------------------------ Buenos Aires: restaurantes
    Rz("el-mercado-faena", "El Mercado (Hotel Faena)", "ba", "Restaurante", "2026-12-29", "Ter 29/12 · jantar em Puerto Madero (opção)",
       {"rest": ["El Mercado (Faena) e Cabaña Las Lilas"], "dia": ["d29"]}, "recomendada",
       "Woki (link oficial do Faena) ou WhatsApp e e-mail do hotel.",
       "Em 29/09 o Woki já mostrava dezembro com vagas para 6. Sugestão nossa: reservar até o fim de outubro.",
       "Preços n/c.",
       "Traje business casual. Jantar das 19h às 0h30. Endereço: Martha Salotti 445.",
       link="https://www.wokiapp.com/restaurante/el-mercado", whatsapp="+54 9 11 4199-4294", telefone="+54 11 4010-9207",
       email="reservasuniverse@faenahotels.com", instagram="@elmercadofaena", dias=60, termos=["El Mercado"],
       fontes=["https://www.faena.com/buenos-aires/dining/el-mercado", "https://www.wokiapp.com/restaurante/el-mercado"],
       confianca="média"),
    Rz("las-lilas", "Cabaña Las Lilas", "ba", "Restaurante", "2026-12-29", "Ter 29/12 · jantar em Puerto Madero (opção)",
       {"rest": ["El Mercado (Faena) e Cabaña Las Lilas"], "dia": ["d29"]}, "recomendada",
       "CoverManager (no site) para até 8 pessoas; também WhatsApp, telefone ou e-mail.",
       "Em 29/09 dezembro já estava aberto no CoverManager.",
       "Bife de chorizo ARS 81 mil (≈ R$ 276); bife de chorizo wagyu ARS 205 mil (carta de jul/2026).",
       "Salão principal, salão II e terraços. Em 31/12 há ceia especial (ver Réveillon).",
       link="https://www.covermanager.com/reservation/module_restaurant/cabana-las-lilas/spanish",
       whatsapp="+54 9 11 3559-9199", telefone="+54 11 4313-1336", email="restaurant@restlaslilas.com.ar",
       instagram="@cabanalaslilasrestaurante", dias=30, termos=["Cabaña Las Lilas"],
       fontes=["https://restaurantlaslilas.com.ar/en/reservations/", "https://www.restaurantlaslilas.com.ar/cartas/Menu.pdf"],
       confianca="alta"),
    Rz("don-julio", "Don Julio", "ba", "Restaurante", "2026-12-30", "Qua 30/12 · jantar (opção)",
       {"rest": ["Don Julio"], "dia": ["d30"]}, "obrigatória",
       "Meitre (até 6 pessoas, com garantia no cartão) ou WhatsApp; sem reserva, só a fila na porta.",
       "A agenda do Meitre já vai até 28/02/2027. Em 29/09 não havia mais jantar para 6 em 30/12; havia almoço para 6 e "
       "jantar para 2 a 4 pessoas. Reservem já.",
       "Bife de chorizo ARS 87 a 95 mil (≈ R$ 296 a 323, jul/2026); menu longo ARS 271 mil por pessoa, pré-pago (set/2026).",
       "Garantia de ARS 35 mil por pessoa no cartão, cobrada só se faltarem; cancelar até 6h antes. Em 31/12 só almoço; 01/01 fechado.",
       link="https://donjulio.meitre.com/", whatsapp="+54 9 11 5311-5668", telefone="+54 11 4507-9873",
       email="info@parrilladonjulio.com.ar", instagram="@donjulioparrilla", dias=92,
       fontes=["https://donjulio.meitre.com/", "https://www.parrilladonjulio.com/", "https://www.canal26.com/turismo/2026/07/23/cuanto-sale-el-bife-de-chorizo-en-la-parrilla-don-julio-de-palermo-en-julio-de-2026/"],
       confianca="alta"),
    Rz("fogon", "Fogón Asado", "ba", "Restaurante", "2026-12-30", "Qua 30/12 · jantar (opção)",
       {"rest": ["Fogón Asado"], "dia": ["d30"]}, "obrigatória",
       "Compra antecipada na plataforma Bokun (botão Book Now do site), escolhendo unidade, menu e harmonização.",
       "Já vende até set/2027. Em 29/09, o jantar de 30/12 às 20h na Uriarte tinha só 2 vagas; a unidade Gorriti 3780 "
       "tinha 22 e o almoço na Uriarte, 39. Reservem já.",
       "US$ 121,20 por pessoa no jantar (≈ R$ 667) e US$ 101 no almoço; harmonização de US$ 40 a 85.",
       "Pré-pago; reembolso integral só cancelando com 5 dias. Até 8 pessoas por reserva; idade mínima 14 anos. "
       "Ceia de Réveillon (31/12, 21h): US$ 252,50 com harmonização.",
       link="https://widgets.bokun.io/online-sales/69dc6e2c-da44-4b97-9b30-247ccc45601c/experience/740180",
       email="reservations@fogonasado.com", instagram="@fogonasado", dias=92,
       fontes=["https://fogonasado.com/en/9-course-tasting-menu/", "https://widgets.bokun.io/online-sales/69dc6e2c-da44-4b97-9b30-247ccc45601c/experience/740180"],
       confianca="alta"),
    Rz("la-cabrera", "La Cabrera", "ba", "Restaurante", "2026-12-30", "Qua 30/12 · jantar ou happy hour (opção)",
       {"rest": ["La Cabrera"], "dia": ["d30"]}, "recomendada",
       "Woki (link do site) ou WhatsApp. Para o happy hour, a lista abre ao meio-dia e é feita no local.",
       "O Woki libera cerca de 1 mês à frente; dezembro ainda não estava aberto em 29/09.",
       "Bife de chorizo 400 g ARS 71,5 mil (≈ R$ 243); 800 g ARS 95,9 mil; couvert ARS 5,3 mil (set/2026). "
       "Happy hour das 18h30 às 20h com 40% off.",
       "Horário: 12h–16h e 18h30–1h. Sinal e funcionamento em 31/12 e 01/01: n/c.",
       link="https://wokiapp.com/reservas/la-cabrera", whatsapp="+54 9 11 6875-4000", telefone="+54 11 4831-0325",
       email="info@lacabrera.com.ar", instagram="@lacabrera_bsas", dias=30,
       fontes=["https://lacabrera.com.ar/", "https://www.wokiapp.com/restaurante/la-cabrera"], confianca="média"),
    Rz("la-carniceria", "La Carnicería", "ba", "Restaurante", "2026-12-30", "Qua 30/12 · jantar (alternativa)",
       {"rest": ["La Carnicería"]}, "obrigatória",
       "Meitre (até 8 pessoas) ou WhatsApp.",
       "O Meitre abre 60 dias antes: 30/12 deve abrir por volta de 31/10/2026 (estimativa).",
       "Preços n/c.",
       "Cerca de 25 lugares. A garantia só é devolvida se cancelarem com 48h. De segunda a sexta, só jantar (19h–0h).",
       link="https://lacarniceria.meitre.com/", whatsapp="+54 9 11 3053-8514", email="Lacarniceriax@gmail.com",
       instagram="@xlacarniceriax", dias=60,
       fontes=["https://lacarniceria.com.ar/", "https://lacarniceria.meitre.com/"], confianca="média"),
    Rz("el-preferido", "El Preferido de Palermo", "ba", "Restaurante", "2026-12-30", "Opção para qualquer noite em Palermo",
       {"rest": ["El Preferido de Palermo"]}, "recomendada",
       "O Meitre aceita até 4 pessoas; para 6, liguem ou mandem mensagem para o celular do Instagram (+54 9 11 2881-2969).",
       "O Meitre abre 80 dias antes: 30/12 deve abrir por volta de 11/10/2026 (estimativa).",
       "Bife angosto de 350 g ARS 67 mil (≈ R$ 228); menu longo ARS 94 mil por pessoa, pré-pago.",
       "Garantia de ARS 35 mil por pessoa no cartão. Mesas na calçada; salão interno só se houver lugar na chegada.",
       link="https://elpreferido.meitre.com/", telefone="+54 11 4774-6585", email="hola@elpreferido.com.ar",
       instagram="@elpreferidodepalermo", dias=80,
       fontes=["https://elpreferido.meitre.com/", "https://www.instagram.com/elpreferidodepalermo/"], confianca="média"),
    Rz("la-brigada", "La Brigada", "ba", "Restaurante", "2026-12-31", "Qui 31/12 · almoço em San Telmo (opção)",
       {"rest": ["La Brigada"], "dia": ["d31"]}, "recomendada",
       "Telefone ou WhatsApp; não há reserva online.",
       "Sem política publicada: n/c. Confirmem se abre no almoço de 31/12.",
       "Preços n/c.",
       "Terça a domingo, 12h–15h e 20h–24h; fecha às segundas.",
       link="https://labrigada.com.ar/contacto/", whatsapp="+54 9 11 3069-8361", telefone="+54 11 4361-4685",
       email="info@labrigada.com.ar", instagram="@parrillalabrigada",
       fontes=["https://labrigada.com.ar/", "https://labrigada.com.ar/contacto/"], confianca="média"),
    # ------------------------------------------------------------------ Réveillon
    Rz("rev-las-lilas", "Cabaña Las Lilas (ceia de Réveillon)", "ba", "Réveillon", "2026-12-31", "Qui 31/12 · opção A, Puerto Madero",
       {"reveillon": ["A"], "dia": ["d31"]}, "obrigatória",
       "Em 2024 e 2025, por telefone, WhatsApp ou e-mail; a ceia de 2026 ainda não foi anunciada.",
       "O menu costuma sair no início de dezembro. Sugestão nossa: pedir para entrar na lista em novembro.",
       "2025: ARS 240 mil no salão e 275 mil no terraço (≈ R$ 816 a 935). 2024: ARS 200 a 230 mil.",
       "Cerca de 7 etapas com vinhos Rutini, DJ e balões à meia-noite no terraço. Menores de 6 anos não pagam.",
       link="https://restaurantlaslilas.com.ar/reservas/", whatsapp="+54 9 11 3559-9199", telefone="+54 11 4313-1336",
       email="restaurant@restlaslilas.com.ar", instagram="@cabanalaslilasrestaurante", dias=45, termos=["Réveillon"],
       fontes=["https://vive.click/cabana-las-lilas-presenta-su-propuesta-gourmet-para-celebrar-fin-de-ano-2025/", "https://ciudadimaginaria.com.ar/2024/12/06/cabana-las-lilas-presenta-su-exclusivo-menu-de-fin-de-ano/"],
       confianca="média"),
    Rz("rev-villegas", "Villegas Resto & Grill (ceia de Réveillon)", "ba", "Réveillon", "2026-12-31", "Qui 31/12 · opção A, Puerto Madero",
       {"reveillon": ["A"], "dia": ["d31"]}, "obrigatória",
       "Em 2025, a ceia foi reservada pelo telefone; mesas comuns pelo Meitre ou WhatsApp.",
       "O Meitre abre 60 dias antes: 31/12 deve abrir por volta de 01/11/2026 (estimativa).",
       "2025: ARS 250 mil no salão, 270 mil na galeria e 290 mil ao ar livre (≈ R$ 850 a 986).",
       "Cinco etapas, vinhos e opção vegana; depois DJ e festa até as 4h. Fica no Dique 3, perto dos fogos.",
       link="https://villegasresto.meitre.com/", whatsapp="+54 9 11 4935-2375", telefone="+54 11 4343-0108",
       email="info@villegasresto.com.ar", instagram="@villegasresto", dias=60, termos=["Réveillon"],
       fontes=["https://www.lanacion.com.ar/que-sale/ano-nuevo-en-buenos-aires-donde-cenar-el-31-de-diciembre-con-menu-especial-brindis-y-mesa-dulce-nid26122025/", "https://villegasresto.com.ar/contacto/"],
       confianca="média"),
    Rz("rev-siga-la-vaca", "Siga la Vaca (ceia de Réveillon)", "ba", "Réveillon", "2026-12-31", "Qui 31/12 · Puerto Madero",
       {"reveillon": ["A"], "dia": ["d31"]}, "obrigatória",
       "Em 2025, só por mensagem no Instagram @sigalavaca, a partir de 02/12.",
       "Em 2025 a ceia foi anunciada 29 dias antes e ainda havia vagas em 23/12, perto de esgotar.",
       "Ceia de 2026: n/c. A tarifa normal (que não vale no Natal nem no Ano-Novo) é ARS 63.900 com 1 bebida (≈ R$ 217).",
       "Rodízio de churrasco a cerca de 1 km dos fogos do Dique 3. Vejam a verificação completa em Travessia e Réveillon.",
       link="https://www.instagram.com/sigalavaca/", telefone="+54 11 4315-6801", instagram="@sigalavaca", dias=29,
       termos=["Réveillon"],
       fontes=["https://sigalavaca.com/", "https://www.instagram.com/p/DRxahwKjBU-/"], confianca="média"),
    Rz("rev-la-carniceria", "La Carnicería (ceia de Réveillon)", "ba", "Réveillon", "2026-12-31", "Qui 31/12 · opção B, Palermo",
       {"reveillon": ["B"], "dia": ["d31"]}, "obrigatória",
       "Em 2025, pelo Meitre.",
       "O Meitre abre 60 dias antes: 31/12 deve abrir por volta de 01/11/2026 (estimativa).",
       "2025: ARS 200 mil por pessoa (≈ R$ 680).",
       "Menu de 2025: choripán, vitel toné, bife, leitão e flan, com vinhos Catena Zapata. Garantia devolvida só com 48h.",
       link="https://lacarniceria.meitre.com/", whatsapp="+54 9 11 3053-8514", instagram="@xlacarniceriax", dias=60,
       termos=["Réveillon"],
       fontes=["https://www.lanacion.com.ar/que-sale/ano-nuevo-en-buenos-aires-donde-cenar-el-31-de-diciembre-con-menu-especial-brindis-y-mesa-dulce-nid26122025/"],
       confianca="média"),
    Rz("rev-lo-de-jesus", "Lo de Jesús (ceia de Réveillon)", "ba", "Réveillon", "2026-12-31", "Qui 31/12 · opção B, Palermo",
       {"reveillon": ["B"], "dia": ["d31"]}, "obrigatória",
       "Telefone ou WhatsApp (o site e o Meitre estão fora do ar).",
       "O menu de 2024 saiu entre 11 e 13/12. Sugestão nossa: mandar mensagem no início de dezembro.",
       "2025: ARS 150 mil por pessoa (≈ R$ 510).",
       "Gurruchaga 1406, Palermo. Recepção com Aperol, entradas, prato à escolha, sobremesa e brinde, com vinhos Salentein.",
       whatsapp="+54 9 11 3943-1734", telefone="+54 11 4832-6011", instagram="@lodejesus", dias=30, termos=["Réveillon"],
       fontes=["https://www.timeout.com/es/buenos-aires/ano-nuevo-2026-navidad-como-festejar-donde-celebrar"], confianca="média"),
    Rz("rev-enero", "Enero (festa de Réveillon)", "ba", "Réveillon", "2026-12-31", "Qui 31/12 · opção C, Costanera Norte",
       {"reveillon": ["C"], "dia": ["d31"]}, "obrigatória",
       "Meitre ou WhatsApp.",
       "O Meitre abre 90 dias antes: 31/12 deve abrir por volta de 02/10/2026 (estimativa).",
       "2025: US$ 150 por adulto (≈ R$ 825).",
       "Av. Rafael Obligado 7180. Em 2025: início às 20h, open bar, música ao vivo, DJ, fogos e estacionamento. Cobram garantia ao reservar.",
       link="https://enero.meitre.com/", whatsapp="+54 9 11 2597-7180", email="info@enerocostanera.com",
       instagram="@enerocostanera", dias=90, termos=["Réveillon"],
       fontes=["https://www.somosohlala.com/lifestyle/gastronomia/donde-cenar-en-ano-nuevo-2025-en-buenos-aires-restaurantes-menus-y-precios-nid05122025", "https://www.enerocostanera.com/"],
       confianca="média"),
    # ------------------------------------------------------------------ Buenos Aires: atrações
    Rz("recoleta", "Cementerio de la Recoleta", "ba", "Atração", "2026-12-30", "Qua 30/12 · 9h",
       {"ponto": ["Cementerio de la Recoleta"], "dia": ["d30"]}, "recomendada",
       "EntradasBA ('Visita Cementerio de la Recoleta (Particular)', setor Extranjeros) ou na entrada, só com cartão.",
       "A venda online abre 1 dia antes; comprem na véspera ou na porta.",
       "ARS 25.370 para estrangeiros (≈ R$ 86).",
       "Todos os dias, 9h–17h. Visitas guiadas grátis em espanhol. Entrada pela Junín 1760.",
       link="https://entradasba.buenosaires.gob.ar/evento/a4e19328-5889-4c3e-9ca2-202c39f3e1f9", dias=1,
       termos=["Cementerio de la Recoleta"],
       fontes=["https://entradasba.buenosaires.gob.ar/establecimientos/85", "https://buenosaires.gob.ar/gcaba_historico/gobierno/gestion-comunal/cementerios-de-la-ciudad/visitas-turisticas-al-cementerio-de-la-recoleta"],
       confianca="alta"),
    Rz("malba", "MALBA", "ba", "Atração", "2026-12-30", "Qua 30/12 · 16h",
       {"ponto": ["MALBA"], "dia": ["d30"]}, "não precisa",
       "Online, escolhendo o dia, ou na bilheteria; não exige reserva.",
       "Não precisa comprar antes; online só agiliza a entrada.",
       "ARS 14.000 (≈ R$ 48); às quartas ARS 7.000, e 30/12 é quarta.",
       "Fecha às terças; 31/12 fecha às 18h; 01/01 fechado.",
       link="https://malba.liit.com.ar/decidir/", telefone="+54 11 4808-6500", email="informes@malba.org.ar",
       fontes=["https://malba.org.ar/visitar/"], confianca="alta"),
    Rz("museo-evita", "Museo Evita", "ba", "Atração", "2026-12-30", "Qua 30/12 · fim da tarde",
       {"ponto": ["Museo Evita"], "dia": ["d30"]}, "não precisa",
       "Ingresso com audioguia (tem português) na loja online, por data; visita guiada grátis às 16h, em espanhol, por ordem de chegada.",
       "Não precisa comprar antes.",
       "ARS 17.000 para estrangeiros (≈ R$ 58).",
       "Terça a domingo, 11h–19h; fechado em 24, 25 e 31/12 e 01/01; abre em 29 e 30/12 e 02/01.",
       link="https://www.tiendamuseoevita.com/booking-calendar/servicio-de-audiogu%C3%ADa", telefone="+54 11 4809-3168",
       email="contacto@museoevita.org.ar", instagram="@museoevita", termos=["Museo Evita"],
       fontes=["https://museoevita.org.ar/ubicacion-y-contacto/", "https://museoevita.org.ar/audioguia/"], confianca="média"),
    Rz("ecoparque", "Ecoparque", "ba", "Atração", "2027-01-01", "Sex 01/01 · 14h",
       {"extra": ["Ecoparque"], "dia": ["d01"]}, "obrigatória",
       "Ingresso por data no site oficial. Deixou de ser grátis para estrangeiros em 17/06/2026.",
       "A venda abre cerca de 1 mês antes (em 29/09 ia até 31/10); comprem quando janeiro abrir.",
       "ARS 22.650 por estrangeiro adulto (≈ R$ 77); grátis para maiores de 65 anos.",
       "Terça a domingo e feriados, 11h–17h30; fecha às segundas e com chuva. Funcionamento em 01/01: n/c.",
       link="https://ecoparque.buenosaires.gob.ar/ticketera/elegir/ecoparque-entrada-general", telefone="147",
       instagram="@ecoparqueba", dias=30,
       fontes=["https://ecoparque.buenosaires.gob.ar/ticketera/elegir/ecoparque-entrada-general", "https://buenosaires.gob.ar/gcaba_historico/noticias/ecoparque-cobraran-entrada-turistas-pero-el-ingreso-seguira-siendo"],
       confianca="alta"),
    Rz("salon-1923", "Salón 1923 (rooftop do Palacio Barolo)", "ba", "Atração", "2027-01-01", "Sex 01/01 · 19h (abertura nesse dia: n/c)",
       {"extra": ["Salón 1923 (rooftop do Palacio Barolo)"], "dia": ["d01"]}, "obrigatória",
       "Reserva online com pagamento de 100% (quem não mora na Argentina escolhe 'transferencia' e pede link de PayPal). "
       "Grupos com mais de 12 pessoas, por mensagem.",
       "O site não informa a janela. Sugestão nossa: 3 semanas antes.",
       "Preço da sessão n/c; cardápio à la carte de ARS 4.500 a 40.000 por item (abr/2026).",
       "Quarta a segunda, 9h–21h; fecha às terças. Sessões: coquetéis qua 18h30, 20h e 21h30; tapeo qui a seg 19h e 21h; "
       "lanche sex a seg 17h. Terraços descobertos. Cancelar ou remarcar até 2h antes. 31/12 e 01/01: n/c.",
       link="https://www.reservaonline.support/salon1923/index.html", whatsapp="+54 9 11 3779-8847 (só mensagens)",
       email="reservas@salon1923.com", instagram="@salon_1923", dias=21, termos=["Salón 1923"],
       fontes=["https://salon1923.com/", "https://www.reservaonline.support/salon1923/index.html"], confianca="média"),
    Rz("barolo-gourmet", "Barolo Gourmet", "ba", "Atração", "2026-12-31", "Qui 31/12 ou sex 01/01 (funcionamento nessas datas: n/c)",
       {"extra": ["Barolo Gourmet (visita guiada com gastronomia)"]}, "obrigatória",
       "Compra online com pagamento de 100%; não residentes pedem link de PayPal no campo de comentários.",
       "O site não informa a janela. Sugestão nossa: 2 semanas antes.",
       "ARS 88.000 para não residentes (≈ R$ 299).",
       "Só quinta e sexta, 18h30–21h: visita, 1 tapa e 1 drink no Salón 1923. Guia em espanhol e inglês. Cancelamento grátis até 6h antes.",
       link="https://palaciobarolotours.com.ar/barolo-gourmet/", whatsapp="+54 9 11 6915-2385 (só mensagens)",
       telefone="+54 11 3221-1331", email="info@palaciobarolotours.com.ar", instagram="@palaciobarolotours", dias=14,
       fontes=["https://palaciobarolotours.com.ar/barolo-gourmet/"], confianca="média"),
    Rz("barolo-visita", "Palacio Barolo (visita guiada)", "ba", "Atração", None, "Livre: segunda e quarta a domingo, inclusive feriados",
       {"ponto": ["Palacio Barolo"]}, "obrigatória",
       "Reserva e pagamento de 100% online (não residentes pedem link de PayPal).",
       "O site não informa a janela. Sugestão nossa: 2 semanas antes.",
       "ARS 54.000 para não residentes (≈ R$ 184). A página do tour ainda mostra ARS 16.800, valor desatualizado.",
       "Cerca de 90 min em espanhol e inglês (sem português); 8 andares de escada; não abre às terças.",
       link="https://palaciobarolotours.com.ar/visitas-guiadas-diurnas/", whatsapp="+54 9 11 6915-2385 (só mensagens)",
       telefone="+54 11 3221-1331", email="info@palaciobarolotours.com.ar", instagram="@palaciobarolotours",
       fontes=["https://palaciobarolotours.com.ar/visitas-guiadas-diurnas/"], confianca="média"),
    Rz("colon", "Teatro Colón (visita guiada)", "ba", "Atração", "2027-01-02", "Sáb 02/01 · em português às 11h45 ou 16h",
       {"ponto": ["Teatro Colón"], "dia": ["d02"]}, "recomendada",
       "Online no EntradasBA (opção 'Visita Guiada - POR') ou na bilheteria da Tucumán 1171; não aceitam moeda estrangeira.",
       "O calendário abre cerca de 1 mês à frente; comprem assim que janeiro/2027 aparecer (início de dezembro).",
       "ARS 34.000 para estrangeiros (≈ R$ 116); menores de 7 anos não pagam.",
       "Visita de 50 min; cheguem 15 min antes. Fechado em 24, 25 e 31/12 e 01/01; sábado 02/01 funciona.",
       link="https://entradasba.buenosaires.gob.ar/visitas/109", dias=30, termos=["Teatro Colón"],
       fontes=["https://teatrocolon.org.ar/visitas-guiadas/", "https://entradasba.buenosaires.gob.ar/visitas/109"],
       confianca="alta"),
    Rz("congreso", "Congreso (visita guiada)", "ba", "Atração", None, "Livre: segunda a sexta (e fins de semana no Senado)",
       {"ponto": ["Congreso"]}, "recomendada",
       "Reserva grátis pelo formulário do Senado ou da Câmara; sem reserva, entra por ordem de chegada se houver vaga.",
       "As vagas abrem de 5 a 10 dias antes.",
       "Grátis.",
       "Cerca de 60 min, sem português; levem passaporte. Pode ser suspensa em dia de sessão.",
       link="https://www.senado.gob.ar/visitasguiadas", telefone="+54 11 2822-3000", email="visitasguiadas@senado.gob.ar",
       fontes=["https://www.senado.gob.ar/visitasguiadas", "https://www.hcdn.gob.ar/secgralpres/dcultura/visitas-guiadas/"],
       confianca="alta"),
    Rz("casa-rosada", "Museo Casa Rosada", "ba", "Atração", None, "Livre: quarta a domingo",
       {"ponto": ["Museo Casa Rosada"]}, "não precisa",
       "Museu com entrada livre, sem reserva. As visitas individuais ao palácio estariam suspensas (fonte secundária).",
       "Não precisa.",
       "Grátis.",
       "Quarta a domingo, 11h–18h (última entrada 17h30); fecha segunda e terça.",
       link="https://www.argentina.gob.ar/secretariageneral/museo-casa-rosada/visita-el-museo-casa-rosada",
       email="museo@presidencia.gob.ar",
       fontes=["https://www.argentina.gob.ar/secretariageneral/museo-casa-rosada/visita-el-museo-casa-rosada"], confianca="baixa"),
    Rz("jardin-japones", "Jardín Japonés", "ba", "Atração", None, "Livre: todos os dias",
       {"ponto": ["Jardín Japonés"]}, "não precisa",
       "Bilheteria na Av. Casares 3500; não há venda online.",
       "Não precisa.",
       "ARS 24.000 para não residentes (≈ R$ 82).",
       "Todos os dias, inclusive feriados, 10h–18h45; não fecha com chuva. 31/12 e 01/01: n/c.",
       link="https://jardinjapones.org.ar/", whatsapp="+54 11 2257-2130", instagram="@jardinjapones",
       fontes=["https://jardinjapones.org.ar/"], confianca="alta"),
    Rz("manzana", "Manzana de las Luces", "ba", "Atração", None, "Livre: quarta a sexta às 15h15",
       {"ponto": ["Manzana de las Luces"]}, "não precisa",
       "Visita guiada grátis por ordem de chegada (40 vagas), saindo da Perú 222.",
       "Não precisa. Os túneis (sábado e domingo) exigem horário online e estavam sem vagas em 29/09.",
       "Grátis.",
       "Visita de 60 min, suspensa com chuva.",
       link="https://manzanadelasluces.cultura.gob.ar/info/visitas/",
       fontes=["https://manzanadelasluces.cultura.gob.ar/info/visitas/"], confianca="média"),
]

# Verificação do Réveillon "por cerca de R$ 220 com bebidas" em Puerto Madero
REVEILLON_VERIFICACAO = {
    "veredito": "Parcialmente confirmado",
    "explicacao": ("Os cerca de R$ 220 existem: são a tarifa normal do Siga la Vaca, rodízio de churrasco em Puerto "
                   "Madero (ARS 63.900 no fim de semana e véspera de feriado, com 1 bebida por pessoa, não é open bar). "
                   "Mas o próprio site avisa que esse preço não vale no Natal nem no Ano-Novo. O jantar de Réveillon "
                   "tem preço à parte, ainda não publicado; em 2025 a reserva foi só por mensagem no Instagram."),
    "principal": {
        "nome": "Siga la Vaca (rodízio de churrasco)",
        "endereco": "Av. Alicia Moreau de Justo 1714, Puerto Madero",
        "inclui": ("Tarifa normal: churrasco, mesa fria e saladas à vontade, 1 bebida por pessoa (cerveja, "
                   "refrigerante, água ou 1 garrafa de vinho da casa) e 1 sobremesa. Itens do Réveillon: n/c; em 2022 "
                   "incluía churrasco à vontade, sobremesa, champanhe e mesa de doces."),
        "preco_pessoa": ("Tarifa normal desde 01/09/2026: ARS 63.900 (sexta à noite, fim de semana, feriado e véspera). "
                         "Réveillon 2026: n/c."),
        "preco_reais": ("Tarifa normal ≈ R$ 217. Réveillon: estimativa não confirmada de R$ 650 a 850, pela proporção "
                        "entre a ceia e a tarifa normal em 2022."),
        "total_6": "Tarifa normal ≈ R$ 1.304. Réveillon: n/c (estimativa de R$ 3.900 a 5.100).",
        "horario": "Todos os dias, das 12h à 1h. Horário da ceia: n/c.",
        "como_reservar": ("Réveillon 2025: só por mensagem no Instagram @sigalavaca, divulgado em 02/12. "
                          "Dias normais: reserva pelo Meitre ou telefone."),
        "antecedencia": ("Em 2025 a ceia foi anunciada 29 dias antes e ainda havia vagas em 23/12, com aviso de que "
                         "estavam acabando. Acompanhem o Instagram a partir do fim de novembro."),
        "obs": ("31/12/2026 é quinta-feira. A queima de fogos pública no Dique 3 (Puente de la Mujer) é gratuita e "
                "fica a cerca de 1 km dali."),
        "link": "https://sigalavaca.meitre.com/",
        "telefone": "+54 11 4315-6801",
        "instagram": "@sigalavaca",
    },
    "alternativas": [
        {"nome": "Siga la Vaca (ceia de Réveillon)", "bairro": "Puerto Madero", "inclui": "Rodízio, sobremesa e brinde (formato de 2022)",
         "preco_pessoa": "n/c (não publicado)", "preco_reais": "estimativa R$ 650 a 850", "total_6": "R$ 3.900 a 5.100 (estimativa)",
         "link": "https://www.instagram.com/sigalavaca/"},
        {"nome": "Áncora", "bairro": "Puerto Retiro, a 3 km de Puerto Madero", "inclui": "Menu de 3 passos com vinhos, espumante, refrigerante e café",
         "preco_pessoa": "ARS 120.000 (2025)", "preco_reais": "≈ R$ 408", "total_6": "≈ R$ 2.450",
         "link": "https://www.instagram.com/ancora_ba/"},
        {"nome": "Enero", "bairro": "Costanera Norte, a 8 km", "inclui": "Jantar, open bar, mesa de doces, música ao vivo, DJ e fogos",
         "preco_pessoa": "US$ 150 (2025)", "preco_reais": "≈ R$ 825", "total_6": "≈ R$ 4.950",
         "link": "https://enero.meitre.com"},
        {"nome": "Cabaña Las Lilas", "bairro": "Puerto Madero", "inclui": "Menu de 7 passos com vinhos Rutini, DJ e balões à meia-noite",
         "preco_pessoa": "ARS 240 a 275 mil (2025)", "preco_reais": "≈ R$ 816 a 935", "total_6": "≈ R$ 4.900 a 5.600",
         "link": "https://restaurantlaslilas.com.ar"},
        {"nome": "Villegas Resto & Grill", "bairro": "Puerto Madero, Dique 3", "inclui": "Menu de 5 passos, vinhos, espumante, mesa de doces, DJ e festa até 4h",
         "preco_pessoa": "ARS 250 a 290 mil (2025)", "preco_reais": "≈ R$ 850 a 986", "total_6": "≈ R$ 5.100 a 5.900",
         "contato": "Tel. +54 11 4343-0108 / WhatsApp +54 9 11 4935-2375"},
        {"nome": "La Parolaccia Puerto Madero", "bairro": "Puerto Madero", "inclui": "Massas, peixes e carnes; água, refrigerante e cerveja à vontade; vinho e brinde com Chandon",
         "preco_pessoa": "ARS 260 mil em dinheiro / 290 mil no cartão (2025)", "preco_reais": "≈ R$ 884 a 986", "total_6": "≈ R$ 5.300 a 5.900",
         "link": "https://www.laparolaccia.com"},
        {"nome": "Puerto Cristal", "bairro": "Puerto Madero", "inclui": "Jantar com show, bebida livre (vinho, espumante e cerveja), DJ e pista",
         "preco_pessoa": "US$ 270 (2025)", "preco_reais": "≈ R$ 1.485", "total_6": "≈ R$ 8.900",
         "link": "https://puerto-cristal.com.ar/"},
    ],
    "nota": ("Valores de 2025 convertidos a R$ 1 = ARS 294 e US$ 1 = R$ 5,50. Os de 2026 ainda não saíram; o Siga la Vaca "
             "subiu 18,5% em nove meses, então contem com reajuste parecido."),
}
